import type { MenuItem } from "../../../shared/types/menu.types";

export const mockMenuData: MenuItem[] = [
  {
    menuId: 0,
    menuName: "User Management",
    parentMenuId: null,
    orderNo: 1,
    isAssigned: true,
    routeUrl: null,
    icon: "users",
    children: [
      {
        menuId: 1,
        menuName: "User DashBoard",
        parentMenuId: 0,
        orderNo: 1,
        isAssigned: true,
        routeUrl: "/user-management/dashboard",
        icon: "layout-dashboard",
        children: null,
      },
      {
        menuId: 2,
        menuName: "Registered User",
        parentMenuId: 0,
        orderNo: 2,
        isAssigned: true,
        routeUrl: "/user-management/registered-user",
        icon: "user-check",
        children: null,
      },
      {
        menuId: 3,
        menuName: "New Users",
        parentMenuId: 0,
        orderNo: 2,
        isAssigned: false,
        routeUrl: "/user-management/new-users",
        icon: "user-plus",
        children: null,
      },
    ],
  },
  {
    menuId: 4,
    menuName: "Fleet Management",
    parentMenuId: null,
    orderNo: 2,
    isAssigned: true,
    routeUrl: null,
    icon: "truck",
    children: [
      {
        menuId: 5,
        menuName: "Vendor",
        parentMenuId: 4,
        orderNo: 1,
        isAssigned: true,
        routeUrl: "/fleet-management/vendor",
        icon: "building-2",
        children: null,
      },
      {
        menuId: 6,
        menuName: "Driver",
        parentMenuId: 4,
        orderNo: 2,
        isAssigned: true,
        routeUrl: "/fleet-management/driver",
        icon: "id-card",
        children: null,
      },
      {
        menuId: 8,
        menuName: "Vehicle",
        parentMenuId: 4,
        orderNo: 3,
        isAssigned: false,
        routeUrl: null,
        icon: "car",
        children: [
          {
            menuId: 9,
            menuName: "add Vehicle",
            parentMenuId: 8,
            orderNo: 4,
            isAssigned: false,
            routeUrl: "/fleet-management/vehicle/add",
            icon: "plus-circle",
            children: null,
          },
        ],
      },
    ],
  },
];
